version: "3"
services:
#  main:
#    container_name: client-service
#    build:
#      context: .
#    env_file:
#        - .env
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - ${APP_PORT}:${APP_PORT}
#      - 9229:9229
#    command: npm run start
#    depends_on:
#      - postgresql
#    restart: always

  postgresql:
    container_name: postgres_order
    image: postgres:12
    restart: always
    env_file:
      - .env
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      PG_DATA: /var/lib/postgresql/data
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
#      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_nodejs
networks:
  rabbitmq_nodejs:
    driver: bridge